udd:
  build: .
  ports:
    - "8080:8080"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - "/usr/local/bin/docker:/usr/bin/docker"
  links:
    - registry:registry

registry:
  image: registry:2
  ports:
    - "5000:5000"